### ISSUE TITLE
enum names are not allowed to have - 

### ISSUE THREAD

**Issue by arbela-cyberillium** [supabase/pg_graphql#356] opened 2023-05-14 08:22 UTC
**Describe the bug**
I get an error like so

``` json
{
  "errors": [
    {
      "message": "Names must only contain [_a-zA-Z0-9] but \"Open-Updated\" does not.",
      "extensions": {},
      "stack": "GraphQLError: Names must only contain [_a-zA-Z0-9] but \"Open-Updated\" does not.\n    at s (https://app.supabase.com/_next/static/chunks/5984-de967ecce9f960c5.js:1:85640)\n    at a (https://app.supabase.com/_next/static/chunks/5984-de967ecce9f960c5.js:1:85932)\n    at https://app.supabase.com/_next/static/chunks/5984-de967ecce9f960c5.js:1:95855\n    at Array.map (<anonymous>)\n    at new ie (https://app.supabase.com/_next/static/chunks/5984-de967ecce9f960c5.js:1:95699)\n    at https://app.supabase.com/_next/static/chunks/5984-de967ecce9f960c5.js:1:133578\n    at https://app.supabase.com/_next/static/chunks/5984-de967ecce9f960c5.js:1:133742\n  
```

relevent scheme snippet

``` SQL
CREATE TYPE public.issue_status AS enum (
    'New',
    'Open',
    'Open-Updated',
    'Partially Mitigated',
    'Partially Patched',
    'Mitigated',
    'Conflict Reports',
    'Snooze',
    'Dismissed',
    'Closed',
    'Closed (scan)',
    'Closed (manual)',
    'Closed (workflow)'
);
```

**Comment by olirice** [comment] 2023-05-15 18:43
dupe of #172

**Closed by olirice** 2023-05-15 18:43 UTC
Labels: triage-required
