### ISSUE TITLE
Cannot save URL-encoded strings

### ISSUE THREAD

**Issue by mayone-du** [supabase/pg_graphql#216] opened 2022-10-01 03:34 UTC
**Describe the bug**
I get an error when trying to save an url encoded string using GraphQL.

**To Reproduce**
1. Access to the environment built for bug reporting → https://supabase-graphql-encoded-string.vercel.app/ 
source https://github.com/mayone-du/playground/tree/main/report/supabase-graphql-encoded-string
2. type `%E3%81%BB%E3%81%92` to sdk and graphql forms.
3. An error occurred in graphql form.

**Expected behavior**
Both are stored correctly.

**Screenshots**
<img width="1372" alt="スクリーンショット 2022-10-01 12 32 22" src="https://user-images.githubusercontent.com/70831966/193385797-9e5ebdb2-fc3c-4b7b-b7e3-2f40239bdeda.png">

**Versions:**
 - PostgreSQL: [e.g. 14.1]
 - pg_graphql commit ref: ea2ab60

**Additional context**
there is no problem when saving from the dashboard.

**Comment by olirice** [comment] 2022-10-03 15:24
wow, that's an awesome reproducible example setup 💯🥇!  

this issue is a duplicate of #211 and was resolved in #212 

That fix will be rolling out on the supabase platform in the next few days but I can get project ref `nhezasnlnwpyqoyumdhd` updated for you today if you give me the thumbs up (no down time required)

**Closed by olirice** 2022-10-03 15:24 UTC
Labels: duplicate
