### ISSUE TITLE
GraphiQL docs not loading due to error fetching schema

### ISSUE THREAD

**Issue by ian-s-mcb** [supabase/pg_graphql#377] opened 2023-07-07 18:56 UTC
_Sorry if this issue belongs elsewhere. Feel free to redirect me to the right repo. Thank you!_

**Describe the bug**

Unlike on the self-hosted Supabase setup via Docker, the GraphiQL editor on the hosted app.supabase.com throws errors that disable the docs feature but do allow queries to be executed.

**To Reproduce**
1. Create a new project on app.supabase.com
2. Create a table using the SQL Editor page
3. Navigate to the API Docs -> GraphiQL page

**Expected behavior**

To be able to browse the docs for my GraphQL API.

**Screenshots**

![screenshot-graphiql_issue-1](https://github.com/supabase/pg_graphql/assets/2540024/a81eba31-b0cd-4fb1-b613-613601802883)
![screenshot-graphiql_issue-2](https://github.com/supabase/pg_graphql/assets/2540024/f3b3b321-ffc5-45c4-bd5d-d526294628f7)

**Versions:**
* pg_graphql v.1.2.2 (as returned by: `select * from pg_available_extensions where name = 'pg_graphql';`)
* PostgreSQL 15.1 (Ubuntu 15.1-1.pgdg20.04+1) (as returned by `select version();`)

**Additional context**
* If it's helpful for an admin to pull up the account/project that shows this issue, the following url should identify it in the dashboard: https://app.supabase.com/project/bagsxvvlcxltwrhrvctu/api/graphiql
* The following is the error trace from the first screenshot:
```json
{
  "errors": [
    {
      "message": "Names must only contain [_a-zA-Z0-9] but \"aead-ietf\" does not.",
      "extensions": {},
      "stack": "u@https://app.supabase.com/_next/static/chunks/4231-d56b093093772f41.js:1:36586\ns@https://app.supabase.com/_next/static/chunks/4231-d56b093093772f41.js:1:85601\na@https://app.supabase.com/_next/static/chunks/4231-d56b093093772f41.js:1:85893\n67950/ie/this._values<@https://app.supabase.com/_next/static/chunks/4231-d56b093093772f41.js:1:95816\nie@https://app.supabase.com/_next/static/chunks/4231-d56b093093772f41.js:1:95660\n80707/h/h</<@https://app.supabase.com/_next/static/chunks/4231-d56b093093772f41.js:1:133539\n80707/h/h</<@https://app.supabase.com/_next/static/chunks/4231-d56b093093772f41.js:1:133703\n80707/h/h<@https://app.supabase.com/_next/static/chunks/4231-d56b093093772f41.js:1:134131\nr@https://app.supabase.com/_next/static/chunks/4231-d56b093093772f41.js:1:45036\nh@https://app.supabase.com/_next/static/chunks/4231-d56b093093772f41.js:1:132725\n71254/_v/E</<@https://app.supabase.com/_next/static/chunks/966b35fd-3515f03fdeac5969.js:1:288080\n"
    }
  ]
}
```

**Comment by olirice** [comment] 2023-07-09 14:26
hi @ian-s-mcb 

I just responded to the support issue you opened. Copying the same information here in case others hit the same issue


> The issue you're experiencing is https://github.com/supabase/pg_graphql/issues/172
> 
> It occurs when the name of a Postgres enum or one of its variants does not meet there requirements for GraphQL name. Those requirements are `[_A-z0-9]+`. In your case it looks like you have some disallowed characters in the `key_type` postgres enum.
> 
> There is a draft PR https://github.com/supabase/pg_graphql/pull/376 that will add the ability to override enum variant names for GraphQL but in the immediate term the solution would be to change the enum variants to valid GraphQL names `[_A-z0-9]+`

in your case you could resolve by changing `aead-ietf` to `aead_ietf` or `AEAD_IETF` to match GraphQL conventions

note that the API will continue to resolve queries when you hit this issue, only introspection rendering is effected

thanks

----

dupe of #172

**Closed by olirice** 2023-07-09 14:26 UTC
Labels: triage-required

**Comment by nicky-ru** [comment] 2023-07-09 19:22
@olirice without any changes to my tables I started experience this issue this week with the exact same name: "aead-ietf"

**Comment by ian-s-mcb** [comment] 2023-07-09 23:31
@olirice that enum wasn't created by me. Are you familiar with `pgsodium`? I ran the following SQL to list all my enums and that uncooperative enum is associated with `pgsodium`. Does this warrant an issue on supabase/supabase?

```sql
select n.nspname as enum_schema,  
       t.typname as enum_name,  
       e.enumlabel as enum_value
from pg_type t 
   join pg_enum e on t.oid = e.enumtypid  
   join pg_catalog.pg_namespace n ON n.oid = t.typnamespace;
```

| enum_schema | enum_name             | enum_value       |
| ----------- | --------------------- | ---------------- |
| pgsodium    | key_status            | default          |
| pgsodium    | key_status            | valid            |
| pgsodium    | key_status            | invalid          |
| pgsodium    | key_status            | expired          |
| pgsodium    | key_type              | aead-ietf        |
| pgsodium    | key_type              | aead-det         |
| pgsodium    | key_type              | hmacsha512       |
| pgsodium    | key_type              | hmacsha256       |
| pgsodium    | key_type              | auth             |
| pgsodium    | key_type              | shorthash        |
| pgsodium    | key_type              | generichash      |
| pgsodium    | key_type              | kdf              |
| pgsodium    | key_type              | secretbox        |
| pgsodium    | key_type              | secretstream     |
| pgsodium    | key_type              | stream_xchacha20 |
| auth        | aal_level             | aal1             |
| auth        | aal_level             | aal2             |
| auth        | aal_level             | aal3             |
| auth        | code_challenge_method | s256             |
| auth        | code_challenge_method | plain            |
| auth        | factor_status         | unverified       |
| auth        | factor_status         | verified         |
| auth        | factor_type           | totp             |
| auth        | factor_type           | webauthn         |

**Comment by PhilippS93** [comment] 2023-07-10 09:55
Same problem here

**Comment by olirice** [comment] 2023-07-10 15:23
thanks all, we're investigating now

cc @michelp

**Comment by olirice** [comment] 2023-07-10 19:44
okay a fix is expected to merge this afternoon

through the usual channels it may take a few days for it to roll out to all projects

If you need a solution sooner than that:
- if you're not using pgsodium or vault you can drop those extensions to get schema introspection working now
- if you respond with your project_ref/s I'll update the instances as soon as the v1.2.3 pg_graphql release is cut
