### ISSUE TITLE
Overlapping fragment sub-queries are not merged

### ISSUE THREAD

**Issue by kav** [supabase/pg_graphql#237] opened 2022-11-19 17:15 UTC
**Describe the bug**
I've got a structure like
```
 fragment A on Users {
  userId
  role
  organization {
    name
  }
}

query HomeScreenQuery($userId: UUID) {
  usersCollection(filter: { userId: { eq: $userId } }, first: 1) {
    edges {
      node {
        ...A
        userId
        role
        organization {
          preferProjects
        }
      }
    }
  }
}
```
And seeing error
> Payload did not contain a value for field `preferProjectName: preferProjectName`. Check that you are parsing with the same query that was used to fetch the payload

**Expected behavior**
I'd expect the payload to contain the merged result from the fragement and the query. Seems like maybe that level of merging is not yet implemented?

**Versions:**
 - PostgreSQL:  14.1
 - pg_graphql commit ref: '0.4.0'

**Additional context**
A simpler example of overlapping fragments and discussion on expected handling can be seen here:
https://github.com/graphql/graphql-spec/issues/399#issuecomment-370665347

**Comment by olirice** [comment] 2022-11-19 20:26
thanks for opening & the reference to the spec

> Seems like maybe that level of merging is not yet implemented?

correct, the current behavior is never to merge. The backend does resolve both, but one will overwrite the other in the result payload. I'll dig through the edge cases, check where that isn't compliant, and add some notes here

--

In the short term, providing an alias to one or both of the instances of `organization` will cause both selection sets to return (not merged) and is backwards compatible as we update the behavior to be spec compliant

**Comment by kav** [comment] 2022-11-19 21:19
Thanks for the quick reply and great workaround @olirice. You rock!

**Comment by fnimick** [comment] 2023-06-23 21:32
Any word on this? This breaks automatic pagination with some clients that insert duplicate `edges` fields to retrieve cursor information for pagination.

**Comment by olirice** [comment] 2023-06-26 19:23
@fnimick could you please send more info about which clients have that behavior? That may increase the priority of this issue if its a common one

**Comment by fnimick** [comment] 2023-06-26 22:37
In particular, Houdini (the most popular / fully-featured graphql client for Sveltekit) has an automatic pagination feature that inserts a duplicate `edges` subquery to select the cursor for pagination. It's easy to work around by adding an alias to the edges that you are selecting, though.

**Comment by kav** [comment] 2023-06-26 22:53
It's still a bit of a pain for me as well FWIW. One thing that might be worth discussing is the spec behavior seems to be to involve merging the fragments before resolving and which filter, etc keys to use to disambiguate. It sounds, and I haven't reviewed the code as yet so I'm out on a limb here, like you're resolving each separately and then merging.

**Comment by fnimick** [comment] 2023-06-27 00:46
@kav "The backend does resolve both, but one will overwrite the other in the result payload." - you are correct, this behavior is not spec compliant, and apparently it will be updated to be spec compliant in a future release.

**Comment by bryanmylee** [comment] 2023-10-25 04:32
Another point mentioned that might increase priority on this is that overlapping fragments are often located independently of each other.

In a larger application, it's often difficult to make sure every fragment has a unique alias to avoid the overlaps from overwriting each other.

Furthermore, the aliases make it almost impossible to do optimistic local cache mutations with clients like Apollo, since we have to update an increasing number of fields for every fragment, made even more difficult if each fragment depends on different fields.

```tsx
// adding a new child to a parent node
function addChildOptimistically() {
  parent.childrenCollection.edges.push({ // used by XFragment
    node: { ... }
  });
  parent.y_childrenCollection.edges.push({ // used by YFragment
    node: { ... }
  });
  parent.z_childrenCollection.edges.push({ // used by ZFragment
    node: { ... }
  });
  // ...
}
```

If overlapping fragments worked as intended, our team would just prohibit aliases (unless the field has ordering / filter properties), and we can clean up our optimistic update code to:

```tsx
function addChildOptimistically() {
  parent.childrenCollection.edges.push({
    node: { ... }
  });
}
```

**Comment by kav** [comment] 2023-11-02 17:52
Will second Bryan to say the bugs this causes are an absolute pain in the rear to fix. A lot of action at a distance. Fragments basically end up cache poisoning each other.

**Comment by bryanmylee** [comment] 2023-12-15 14:07
I'm working on a fix for this at the moment which involves a custom deep-merge function which properly combines the fragment results instead of overriding the values stored in the key.

However, I need pointers on how fragments should be merged across collections.

If I have two fragments:

```gql
query {
  ...title_query
  ...content_query
}

fragment title_query on Query {
  blogPostCollection {
    edges {
      node {
        title
      }
    }
  }
}

fragment content_query on Query {
  blogPostCollection {
    edges {
      node {
        content
      }
    }
  }
}
```

The result should be (based on experiments with Hasura):

```
{
  "blogPostCollection": {
    "edges": [
      {
        "node": {
          "title": "Blog post 1",
          "content": "Lorem ipsum"
        }
      },
      {
        "node": {
          "title": "Blog post 2",
          "content": "dolor sit"
        }
      }
    ]
  }
}
```

Initially, I thought this meant that every object needed to be uniquely identifiable, even when `id` is not queried for, to allow different fragment results to be merged properly.

However, it seems like Hasura just merges the objects by index and returns an error if two collection fields are requested with different arguments.

```
{
  "errors": [
    {
      "message": "inconsistent arguments between multiple selections of field 'teamConnection'",
      "extensions": {
        "path": "$.selectionSet",
        "code": "validation-failed"
      }
    }
  ]
}
```

Should we take that same approach?

**Comment by imor** [comment] 2023-12-16 02:56
That is a valid approach to follow as per the spec. See [Field Selection Merging](https://spec.graphql.org/October2021/#sec-Field-Selection-Merging) and [Field Collection](https://spec.graphql.org/October2021/#sec-Field-Collection) for details.

**Comment by kav** [comment] 2023-12-16 04:44
@bryanmylee if you take a look at the graphql spec conversation I linked up top it has a solid explanation of how you might allow connections with different parameters in the same payload using unique keys and does a pretty good job walking through the cases.

One big call out and you may be doing the right thing but phrasing it differently than I expect: the merge should happen before resolution. You aren't merging results you should be merging before querying the db. That will have a number of benefits in that a lot of questions about what can be safely merged and what can't will be extremely clear on the query side.

I can add a bit more detail if any of this is unclear or seems nonsensical. Traveling at the moment so a bit of mobile stream of consciousness.

**Comment by bryanmylee** [comment] 2023-12-16 07:03
I was planning on taking the easier approach of merging the results initially, but yes it would be better to normalize the selection properly before querying.

I've currently narrowed the area to look at down to `parser_util.rs`'s `normalize_selection`, but I'm still making sense of it.

**Comment by bryanmylee** [comment] 2023-12-16 19:38
I'm getting the hang of the library. A few questions though: how should we merge the spans and positions of two fields? This isn't really covered by the GraphQL spec and seems to be more of a implementation detail.

**Comment by olirice** [comment] 2023-12-18 16:46
> If two fragments for example have the spans 20:28--30:9 and 8:28--16:9, can we just assume that the merged field will have a selection set with minimal span that encapsulates both merged sets e.g. 8:28--30:9?

that sounds most reasonable to me, I'm not sure what else could be done that would still count as correct

**Comment by bryanmylee** [comment] 2023-12-19 10:24
> > If two fragments for example have the spans 20:28--30:9 and 8:28--16:9, can we just assume that the merged field will have a selection set with minimal span that encapsulates both merged sets e.g. 8:28--30:9?
> 
> that sounds most reasonable to me, I'm not sure what else could be done that would still count as correct

I've updated the PR to include that behaviour, it's ready for your review!

**Comment by olirice** [comment] 2024-07-10 15:16
resolved in https://github.com/supabase/pg_graphql/pull/479

**Closed by olirice** 2024-07-10 15:16 UTC
Labels: GraphQL spec
