### ISSUE TITLE
Add in support for persisted queries

### ISSUE THREAD

**Issue by rnbokade** [supabase/pg_graphql#189] opened 2022-07-06 20:29 UTC
I am here after reading a lot about how exposing graphql endpoint directly especially when the api isn't meant for public interaction use can lead to lot of different attacks. And how one can kinda benefit from delivering persisted queries only.
This can be easily achieved in pg_graphql by 
1. Disable public exposure of resolve procedure.
2. Create new store procedure "gql_query" , which takes query hash and query parameters as arguments
3. Create a table and store query statements against hash
4. When gql_query is hit, internally call the query text stored against hash and parameter from request to "resolve" procedure

**Comment by olirice** [comment] 2022-07-07 13:24
dupe of #16 

I'll add another comment over there to keep it all together

**Closed by olirice** 2022-07-07 13:25 UTC
