### ISSUE TITLE
Feature Request: Query Allowlist

### ISSUE THREAD

**Issue by wolframm** [supabase/pg_graphql#223] opened 2022-10-19 05:33 UTC
# Summary

Ensure that only the operations you use in your own applications can be executed in Postgres DB, preventing malicious (or merely curious) actors from executing operations which may be more expensive than those you have written.

# Rationale
[rationale]: #rationale

Projects that only intend first party clients to use the GraphQL schema should use persisted operations to mitigate attacks against the GraphQL API and to help track the fields that have been used.

# Design
[design]: #design

Design is illustrated on https://www.graphile.org/postgraphile/production/#simple-query-allowlist-persisted-queries--persisted-operations

**Comment by olirice** [comment] 2022-10-19 14:16
dupe of #16 

> preventing malicious (or merely curious) actors from executing operations which may be more expensive than those you have written.

To mitigate this risk, check out the [statement_timeout](https://www.postgresql.org/docs/current/runtime-config-client.html) parameter. By default, the platform sets this value to 2 minutes to accommodate (possibly slow) DDL. That isn't necessary for the `anon` and `authenticated` roles, so you could 

```sql
ALTER ROLE anon SET statement_timeout = '3 seconds';
```
to restrict the maximum cost of a API call

**Closed by olirice** 2022-10-19 14:16 UTC
Labels: duplicate
