### ISSUE TITLE
Stripe wrapper only allows fetching first 100 objects

### ISSUE THREAD

**Issue by thomtrp** [supabase/pg_graphql#521] opened 2024-05-29 10:37 UTC
**Describe the bug**

When performing `pg_graphql` queries on a foreign table imported by the `stripe_fdw`, I cannot fetch more than the first 100 items. Checking the foreign table, I can see I have more items to fetch.

Using raw sql query works well. Trying with the `postgres_fdw` works also well. 

Only `stripe_fdw` combinated with `pg_graphql` seems to have this limit.

**To Reproduce**

1. Using `stripe_fdw`, create a foreign table based on stripe API. For my example, I will use the object customers.
2. Perform a query and get the last cursor. I got 60 items with that first query.
```
query {
  customerCollection {
    edges {
      node {
        __typename
        id: id
      }
      cursor
      __typename
    }
    pageInfo {
      startCursor
      endCursor
      __typename
    }
    __typename
  }
}
```

3. Perform a second query adding `after: <last_cursor>` in `customerCollection` query params. I got only 40 items this time.
4. Perform a third query using the new `last_cursor`. I got an empty answer while I have 165 items in my table.
`{"data": {"customerCollection": {"edges": [], "pageInfo": {"endCursor": null, "__typename": "PageInfo", "startCursor": null}, "__typename": "customerConnection"}}}`

**Expected behavior**

I should be able to fetch my 165 customers and not only the first 100.

**Additional context**

I already opened [an issue ](https://github.com/supabase/pg_graphql/issues/519) related with `stripe_fdw` and `pg_graphql` limitations for stripe foreign table relations.

**Comment by olirice** [comment] 2024-06-04 21:40
pg_graphql doesn't do any unique handling of foreign data wrappers. It treats them identically to tables so its unlikely that we'll be able to resolve your issue in this repo.

Its possibly you're hitting something like this https://github.com/supabase/wrappers/issues/113
from the [stripe docs](https://docs.stripe.com/api/pagination) it looks like you might be getting exactly 1 page of data back with the maximum 100 elements

please also note that putting a foreign data wrapper directly on your API's search path is [not recommended](https://supabase.com/docs/guides/database/database-advisors?queryGroups=lint&lint=0017_foreign_table_in_api)

**Comment by olirice** [comment] 2024-06-04 21:42
In case it helps create a reproducible example, the underlying SQL that your query gets compiled to would be roughly

```sql
(
                with __records as (
                    select
                       *
                    from
                       <your fdw>
                    where
                        true
                    order by
                        <value>
                    limit
                        <value>
                    offset
                        <value>
                ),
                __total_count(___total_count) as (
                    select
                        count(*)
                    from
                        <your fdw>
                    where
                        true
                ),
                select
                    jsonb_build_object('id', id) -- sorted within edge
                from
                    __records foo,
                    __total_count
            )
```

**Comment by olirice** [comment] 2024-08-19 13:05
closing as not relevant to this repo
see https://github.com/supabase/wrappers/issues/113 for this issue

**Closed by olirice** 2024-08-19 13:05 UTC
